### ISSUE TITLE
how can yi 34B be trained?

### ISSUE THREAD

**Issue by BarfingLemurs** [FartyPants/Training_PRO#12]
I can't figure out this model, loading it through transformers would throw errors. I tested a couple of "llamified" versions including gptq. Wanted to see if someone figured it out.

Great work BTW, love the extension, its alot of fun to train text files and the installation is easy. 👍

**Comment by FartyPants** [comment]
yi - you need to get HF llamafied version. It should run.
The original yi renamed layers (it's llama, they just wanted to have their "own")
Normally transformers make auto classes for these situations:
https://huggingface.co/docs/transformers/model_doc/auto

Not sure if they'll make auto class for yi though.

**Comment by BarfingLemurs** [comment]
Ah, thank you for the confirmation!
