### ISSUE TITLE
Failed to load the extension

### ISSUE THREAD

**Issue by krslim** [FartyPants/Training_PRO#4]
Thanks for your work! My oogabooga version is working, but I'm getting the following error with the latest code from this repo:

2023-10-18 19:30:53 ERROR:Failed to load the extension "Training_PRO".
Traceback (most recent call last):
  File "F:\AI\Oobabooga\text-generation-webui\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "F:\AI\Oobabooga\text-generation-webui\extensions\Training_PRO\script.py", line 22, in <module>
    from .custom_scheduler import FPSchedulerTrainer, custom_scheduler_global_update, custom_scheduler_global_setup, custom_scheduler_global_shuffle
ImportError: cannot import name 'custom_scheduler_global_update' from 'extensions.Training_PRO.custom_scheduler' (F:\AI\Oobabooga\text-generation-webui\extensions\Training_PRO\custom_scheduler.py)

Does custom_scheduler.py need to be updated to reflect the recent changes with script.py?

**Comment by SrVill** [comment]
A similar problem. I went back to commit ac4e782. Then there is no problem

**Comment by FartyPants** [comment]
You need to get all the files from here.
The project here is the latest project I'm running on my computer.

**Comment by krslim** [comment]
I'm looking forward to experimenting with the mistral models, thanks again!
